# Generated by Django 5.0 on 2023-12-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_color_quantity_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='size',
        ),
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
