# Generated by Django 5.0.1 on 2024-02-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.inventory'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
