# Generated by Django 5.0.1 on 2024-02-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_inventory_color_alter_inventory_size'),
        ('products', '0018_remove_addtocart_inventory'),
    ]

    operations = [
    ]
