# Generated by Django 5.0.1 on 2024-02-08 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_merge_20240208_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.inventory'),
        ),
    ]
